server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: service_product
              uri: lb://SERVICE_PRODUCT
              predicates:
                - Path=/products/**

            - id: service_authentication
              uri: lb://SERVICE_AUTHENTICATION
              predicates:
                - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
