server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: service_product
              uri: http://localhost:8082
              predicates:
                - Path=/products/**

            - id: service_authentication
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**

